TA_cols <- c("id",
             "COUNTRY",
             "GSA",
             "VESSEL",
             "GEAR",
             "RIGGING",
             "DOORS",
             "YEAR",
             "MONTH",
             "HAUL_NUMBER",
             "SHOOTING_TIME",
             "SHOOTING_LATITUDE",
             "SHOOTING_LONGITUDE",
             "SHOOTING_QUADRANT",
             "SHOOTING_DEPTH",
             "HAULING_TIME",
             "HAULING_LATITUDE",
             "HAULING_LONGITUDE",
             "HAULING_QUADRANT",
             "HAULING_DEPTH",
             "HAUL_DURATION",
             "VALIDITY",
             "DISTANCE",
             "VERTICAL_OPENING",
             "WING_OPENING",
             "BOTTOM_TEMPERATURE_BEGINNING",
             "BOTTOM_TEMPERATURE_END",
             "NUMBER_OF_THE_STRATUM")

TB_cols <- c("id",
             "GENUS",
             "SPECIES",
             "TOTAL_WEIGHT_IN_THE_HAUL",
             "TOTAL_NUMBER_IN_THE_HAUL",
             "NB_OF_FEMALES",
             "NB_OF_MALES",
             "NB_OF_UNDETERMINED")

TC_cols <- c("id",
             "GENUS",
             "SPECIES",
             "LENGTH_CLASSES_CODE",
             "WEIGHT_OF_THE_FRACTION",
             "WEIGHT_OF_THE_SAMPLE_MEASURED",
             "SEX",
             "LENGTH_CLASS",
             "MATURITY",
             "MATSUB",
             "NUMBER_OF_INDIVIDUALS_IN_THE_LENGTH_CLASS_AND_MATURITY_STAGE")
